<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_rating.proto

namespace RatingGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для rating.addScreenTime
 *
 * Generated from protobuf message <code>ratingGrpc.RatingAddScreenTimeRequestStruct</code>
 */
class RatingAddScreenTimeRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     */
    protected $space_id = 0;
    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 screen_time = 3;</code>
     */
    protected $screen_time = 0;
    /**
     * Generated from protobuf field <code>string local_online_at = 4;</code>
     */
    protected $local_online_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $space_id
     *     @type int|string $user_id
     *     @type int|string $screen_time
     *     @type string $local_online_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoRating::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     * @return int|string
     */
    public function getSpaceId()
    {
        return $this->space_id;
    }

    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpaceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->space_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 screen_time = 3;</code>
     * @return int|string
     */
    public function getScreenTime()
    {
        return $this->screen_time;
    }

    /**
     * Generated from protobuf field <code>int64 screen_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScreenTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->screen_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string local_online_at = 4;</code>
     * @return string
     */
    public function getLocalOnlineAt()
    {
        return $this->local_online_at;
    }

    /**
     * Generated from protobuf field <code>string local_online_at = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalOnlineAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->local_online_at = $var;

        return $this;
    }

}

