<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_rating.proto

namespace RatingGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат ответа для rating.updateConversationAnswerState
 *
 * Generated from protobuf message <code>ratingGrpc.RatingUpdateConversationAnswerStateResponseStruct</code>
 */
class RatingUpdateConversationAnswerStateResponseStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     */
    protected $space_id = 0;
    /**
     * Generated from protobuf field <code>string conversation_key = 2;</code>
     */
    protected $conversation_key = '';
    /**
     * Generated from protobuf field <code>int64 answer_time = 3;</code>
     */
    protected $answer_time = 0;
    /**
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>int64 micro_conversation_start_at = 5;</code>
     */
    protected $micro_conversation_start_at = 0;
    /**
     * Generated from protobuf field <code>int64 micro_conversation_end_at = 6;</code>
     */
    protected $micro_conversation_end_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $space_id
     *     @type string $conversation_key
     *     @type int|string $answer_time
     *     @type int|string $created_at
     *     @type int|string $micro_conversation_start_at
     *     @type int|string $micro_conversation_end_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoRating::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     * @return int|string
     */
    public function getSpaceId()
    {
        return $this->space_id;
    }

    /**
     * Generated from protobuf field <code>int64 space_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpaceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->space_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string conversation_key = 2;</code>
     * @return string
     */
    public function getConversationKey()
    {
        return $this->conversation_key;
    }

    /**
     * Generated from protobuf field <code>string conversation_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConversationKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->conversation_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 answer_time = 3;</code>
     * @return int|string
     */
    public function getAnswerTime()
    {
        return $this->answer_time;
    }

    /**
     * Generated from protobuf field <code>int64 answer_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnswerTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->answer_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 micro_conversation_start_at = 5;</code>
     * @return int|string
     */
    public function getMicroConversationStartAt()
    {
        return $this->micro_conversation_start_at;
    }

    /**
     * Generated from protobuf field <code>int64 micro_conversation_start_at = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMicroConversationStartAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->micro_conversation_start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 micro_conversation_end_at = 6;</code>
     * @return int|string
     */
    public function getMicroConversationEndAt()
    {
        return $this->micro_conversation_end_at;
    }

    /**
     * Generated from protobuf field <code>int64 micro_conversation_end_at = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMicroConversationEndAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->micro_conversation_end_at = $var;

        return $this;
    }

}

