<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_rating.proto

namespace RatingGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для system.traceMemory
 *
 * Generated from protobuf message <code>ratingGrpc.SystemTraceMemoryRequestStruct</code>
 */
class SystemTraceMemoryRequestStruct extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoRating::initOnce();
        parent::__construct($data);
    }

}

