<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_sender.proto

namespace SenderGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для сервиса отправки ws
 *
 * Generated from protobuf message <code>senderGrpc.SendWsServiceRequestStruct</code>
 */
class SendWsServiceRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     */
    protected $company_id = 0;
    /**
     * Generated from protobuf field <code>string event = 3;</code>
     */
    protected $event = '';
    /**
     * Generated from protobuf field <code>string channel = 4;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>repeated int64 receiver_user_id_list = 5;</code>
     */
    private $receiver_user_id_list;
    /**
     * Generated from protobuf field <code>repeated int64 users = 6;</code>
     */
    private $users;
    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes event_version_list = 7;</code>
     */
    protected $event_version_list = '';
    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes push_data = 8;</code>
     */
    protected $push_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type int|string $company_id
     *     @type string $event
     *     @type string $channel
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $receiver_user_id_list
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $users
     *     @type string $event_version_list
     *           json поле
     *     @type string $push_data
     *           json поле
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoSender::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event = 3;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>string event = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 4;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 receiver_user_id_list = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReceiverUserIdList()
    {
        return $this->receiver_user_id_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 receiver_user_id_list = 5;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReceiverUserIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->receiver_user_id_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 users = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated int64 users = 6;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->users = $arr;

        return $this;
    }

    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes event_version_list = 7;</code>
     * @return string
     */
    public function getEventVersionList()
    {
        return $this->event_version_list;
    }

    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes event_version_list = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEventVersionList($var)
    {
        GPBUtil::checkString($var, False);
        $this->event_version_list = $var;

        return $this;
    }

    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes push_data = 8;</code>
     * @return string
     */
    public function getPushData()
    {
        return $this->push_data;
    }

    /**
     * json поле
     *
     * Generated from protobuf field <code>bytes push_data = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPushData($var)
    {
        GPBUtil::checkString($var, False);
        $this->push_data = $var;

        return $this;
    }

}

