<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company_cache.proto

namespace CompanyCacheGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат ответа для member.getShortList
 *
 * Generated from protobuf message <code>companyCacheGrpc.MemberGetShortListResponseStruct</code>
 */
class MemberGetShortListResponseStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .companyCacheGrpc.MemberShortInfoStruct member_list = 1;</code>
     */
    private $member_list;
    /**
     * Generated from protobuf field <code>repeated int64 not_found_list = 2;</code>
     */
    private $not_found_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CompanyCacheGrpc\MemberShortInfoStruct[]|\Google\Protobuf\Internal\RepeatedField $member_list
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $not_found_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompanyCache::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .companyCacheGrpc.MemberShortInfoStruct member_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberList()
    {
        return $this->member_list;
    }

    /**
     * Generated from protobuf field <code>repeated .companyCacheGrpc.MemberShortInfoStruct member_list = 1;</code>
     * @param \CompanyCacheGrpc\MemberShortInfoStruct[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CompanyCacheGrpc\MemberShortInfoStruct::class);
        $this->member_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 not_found_list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotFoundList()
    {
        return $this->not_found_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 not_found_list = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotFoundList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->not_found_list = $arr;

        return $this;
    }

}

