<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company_cache.proto

namespace CompanyCacheGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура пользователя
 *
 * Generated from protobuf message <code>companyCacheGrpc.MemberInfoStruct</code>
 */
class MemberInfoStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>int32 npc_type = 3;</code>
     */
    protected $npc_type = 0;
    /**
     * Generated from protobuf field <code>int32 permissions = 4;</code>
     */
    protected $permissions = 0;
    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     */
    protected $created_at = 0;
    /**
     * Generated from protobuf field <code>int32 updated_at = 6;</code>
     */
    protected $updated_at = 0;
    /**
     * Generated from protobuf field <code>int32 company_joined_at = 7;</code>
     */
    protected $company_joined_at = 0;
    /**
     * Generated from protobuf field <code>int32 fullname_updated_at = 8;</code>
     */
    protected $fullname_updated_at = 0;
    /**
     * Generated from protobuf field <code>string fullname = 9;</code>
     */
    protected $fullname = '';
    /**
     * Generated from protobuf field <code>string mbti_type = 10;</code>
     */
    protected $mbti_type = '';
    /**
     * Generated from protobuf field <code>string short_description = 11;</code>
     */
    protected $short_description = '';
    /**
     * Generated from protobuf field <code>string avatar_file_key = 12;</code>
     */
    protected $avatar_file_key = '';
    /**
     * Generated from protobuf field <code>string comment = 13;</code>
     */
    protected $comment = '';
    /**
     * Generated from protobuf field <code>string extra = 14;</code>
     */
    protected $extra = '';
    /**
     * Generated from protobuf field <code>int32 left_at = 15;</code>
     */
    protected $left_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int $role
     *     @type int $npc_type
     *     @type int $permissions
     *     @type int $created_at
     *     @type int $updated_at
     *     @type int $company_joined_at
     *     @type int $fullname_updated_at
     *     @type string $fullname
     *     @type string $mbti_type
     *     @type string $short_description
     *     @type string $avatar_file_key
     *     @type string $comment
     *     @type string $extra
     *     @type int $left_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompanyCache::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>int32 role = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkInt32($var);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 npc_type = 3;</code>
     * @return int
     */
    public function getNpcType()
    {
        return $this->npc_type;
    }

    /**
     * Generated from protobuf field <code>int32 npc_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNpcType($var)
    {
        GPBUtil::checkInt32($var);
        $this->npc_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 permissions = 4;</code>
     * @return int
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>int32 permissions = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPermissions($var)
    {
        GPBUtil::checkInt32($var);
        $this->permissions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int32 created_at = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 updated_at = 6;</code>
     * @return int
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int32 updated_at = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 company_joined_at = 7;</code>
     * @return int
     */
    public function getCompanyJoinedAt()
    {
        return $this->company_joined_at;
    }

    /**
     * Generated from protobuf field <code>int32 company_joined_at = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCompanyJoinedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->company_joined_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fullname_updated_at = 8;</code>
     * @return int
     */
    public function getFullnameUpdatedAt()
    {
        return $this->fullname_updated_at;
    }

    /**
     * Generated from protobuf field <code>int32 fullname_updated_at = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setFullnameUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->fullname_updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     * Generated from protobuf field <code>string fullname = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mbti_type = 10;</code>
     * @return string
     */
    public function getMbtiType()
    {
        return $this->mbti_type;
    }

    /**
     * Generated from protobuf field <code>string mbti_type = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMbtiType($var)
    {
        GPBUtil::checkString($var, True);
        $this->mbti_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string short_description = 11;</code>
     * @return string
     */
    public function getShortDescription()
    {
        return $this->short_description;
    }

    /**
     * Generated from protobuf field <code>string short_description = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setShortDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->short_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string avatar_file_key = 12;</code>
     * @return string
     */
    public function getAvatarFileKey()
    {
        return $this->avatar_file_key;
    }

    /**
     * Generated from protobuf field <code>string avatar_file_key = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatarFileKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar_file_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 13;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 14;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 left_at = 15;</code>
     * @return int
     */
    public function getLeftAt()
    {
        return $this->left_at;
    }

    /**
     * Generated from protobuf field <code>int32 left_at = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setLeftAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->left_at = $var;

        return $this;
    }

}

