<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company_cache.proto

namespace CompanyCacheGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат ответа для session.getInfo
 *
 * Generated from protobuf message <code>companyCacheGrpc.SessionGetInfoResponseStruct</code>
 */
class SessionGetInfoResponseStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string ua_hash = 2;</code>
     */
    protected $ua_hash = '';
    /**
     * Generated from protobuf field <code>string ip_address = 3;</code>
     */
    protected $ip_address = '';
    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     */
    protected $extra = '';
    /**
     * Generated from protobuf field <code>.companyCacheGrpc.MemberInfoStruct member = 5;</code>
     */
    protected $member = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $ua_hash
     *     @type string $ip_address
     *     @type string $extra
     *     @type \CompanyCacheGrpc\MemberInfoStruct $member
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompanyCache::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ua_hash = 2;</code>
     * @return string
     */
    public function getUaHash()
    {
        return $this->ua_hash;
    }

    /**
     * Generated from protobuf field <code>string ua_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUaHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->ua_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip_address = 3;</code>
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ip_address;
    }

    /**
     * Generated from protobuf field <code>string ip_address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.companyCacheGrpc.MemberInfoStruct member = 5;</code>
     * @return \CompanyCacheGrpc\MemberInfoStruct|null
     */
    public function getMember()
    {
        return $this->member;
    }

    public function hasMember()
    {
        return isset($this->member);
    }

    public function clearMember()
    {
        unset($this->member);
    }

    /**
     * Generated from protobuf field <code>.companyCacheGrpc.MemberInfoStruct member = 5;</code>
     * @param \CompanyCacheGrpc\MemberInfoStruct $var
     * @return $this
     */
    public function setMember($var)
    {
        GPBUtil::checkMessage($var, \CompanyCacheGrpc\MemberInfoStruct::class);
        $this->member = $var;

        return $this;
    }

}

