<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_sender.proto

namespace SenderCacheGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для Sender.SendThreadTypingEvent
 *
 * Generated from protobuf message <code>senderCacheGrpc.SenderSendThreadTypingEventRequestStruct</code>
 */
class SenderSendThreadTypingEventRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     */
    private $user_list;
    /**
     * Generated from protobuf field <code>string event = 2;</code>
     */
    protected $event = '';
    /**
     * Generated from protobuf field <code>string event_data = 3;</code>
     */
    protected $event_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $user_list
     *     @type string $event
     *     @type string $event_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoSender::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserList()
    {
        return $this->user_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->user_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_data = 3;</code>
     * @return string
     */
    public function getEventData()
    {
        return $this->event_data;
    }

    /**
     * Generated from protobuf field <code>string event_data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEventData($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_data = $var;

        return $this;
    }

}

