<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура для ответа rating.GetEventCountByInterval
 *
 * Generated from protobuf message <code>companyGrpc.EventCount</code>
 */
class EventCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     */
    protected $day = 0;
    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $year
     *     @type int|string $day
     *     @type int|string $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     * @return int|string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt64($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @return int|string
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt64($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

}

