<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для rating.GetByUserId
 *
 * Generated from protobuf message <code>companyGrpc.RatingGetByUserIdRequestStruct</code>
 */
class RatingGetByUserIdRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>repeated int64 from_date_at_list = 3;</code>
     */
    private $from_date_at_list;
    /**
     * Generated from protobuf field <code>repeated int64 to_date_at_list = 4;</code>
     */
    private $to_date_at_list;
    /**
     * Generated from protobuf field <code>repeated int64 is_from_cache_list = 5;</code>
     */
    private $is_from_cache_list;
    /**
     * Generated from protobuf field <code>int64 company_id = 6;</code>
     */
    protected $company_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int|string $year
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $from_date_at_list
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $to_date_at_list
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $is_from_cache_list
     *     @type int|string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     * @return int|string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt64($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 from_date_at_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFromDateAtList()
    {
        return $this->from_date_at_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 from_date_at_list = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFromDateAtList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->from_date_at_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 to_date_at_list = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getToDateAtList()
    {
        return $this->to_date_at_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 to_date_at_list = 4;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setToDateAtList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->to_date_at_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 is_from_cache_list = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIsFromCacheList()
    {
        return $this->is_from_cache_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 is_from_cache_list = 5;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIsFromCacheList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->is_from_cache_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 6;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

}

