<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат ответа для rating.Get
 *
 * Generated from protobuf message <code>companyGrpc.RatingGetResponseStruct</code>
 */
class RatingGetResponseStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 count = 1;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>int64 updated_at = 2;</code>
     */
    protected $updated_at = 0;
    /**
     * Generated from protobuf field <code>repeated .companyGrpc.TopItem top_list = 3;</code>
     */
    private $top_list;
    /**
     * Generated from protobuf field <code>int64 has_next = 4;</code>
     */
    protected $has_next = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $count
     *     @type int|string $updated_at
     *     @type \CompanyGrpc\TopItem[]|\Google\Protobuf\Internal\RepeatedField $top_list
     *     @type int|string $has_next
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 count = 1;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 2;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .companyGrpc.TopItem top_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopList()
    {
        return $this->top_list;
    }

    /**
     * Generated from protobuf field <code>repeated .companyGrpc.TopItem top_list = 3;</code>
     * @param \CompanyGrpc\TopItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CompanyGrpc\TopItem::class);
        $this->top_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 has_next = 4;</code>
     * @return int|string
     */
    public function getHasNext()
    {
        return $this->has_next;
    }

    /**
     * Generated from protobuf field <code>int64 has_next = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHasNext($var)
    {
        GPBUtil::checkInt64($var);
        $this->has_next = $var;

        return $this;
    }

}

