<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для rating.GetListByDay
 *
 * Generated from protobuf message <code>companyGrpc.RatingGetListByDayRequestStruct</code>
 */
class RatingGetListByDayRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     */
    protected $day = 0;
    /**
     * Generated from protobuf field <code>int64 company_id = 3;</code>
     */
    protected $company_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $year
     *     @type int|string $day
     *     @type int|string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     * @return int|string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int64 year = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt64($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @return int|string
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>int64 day = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt64($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 3;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

}

