<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для rating.GetEventCountByInterval
 *
 * Generated from protobuf message <code>companyGrpc.RatingGetEventCountByIntervalRequestStruct</code>
 */
class RatingGetEventCountByIntervalRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string event = 1;</code>
     */
    protected $event = '';
    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>int64 from_date_at = 3;</code>
     */
    protected $from_date_at = 0;
    /**
     * Generated from protobuf field <code>int64 to_date_at = 4;</code>
     */
    protected $to_date_at = 0;
    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     */
    protected $company_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $event
     *     @type int|string $year
     *     @type int|string $from_date_at
     *     @type int|string $to_date_at
     *     @type int|string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string event = 1;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>string event = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     * @return int|string
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int64 year = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt64($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 from_date_at = 3;</code>
     * @return int|string
     */
    public function getFromDateAt()
    {
        return $this->from_date_at;
    }

    /**
     * Generated from protobuf field <code>int64 from_date_at = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromDateAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->from_date_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 to_date_at = 4;</code>
     * @return int|string
     */
    public function getToDateAt()
    {
        return $this->to_date_at;
    }

    /**
     * Generated from protobuf field <code>int64 to_date_at = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToDateAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->to_date_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

}

