<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для reactions.RemoveInThread
 *
 * Generated from protobuf message <code>companyGrpc.ReactionsRemoveInThreadRequestStruct</code>
 */
class ReactionsRemoveInThreadRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.companyGrpc.ThreadReactionStruct thread_reaction = 1;</code>
     */
    protected $thread_reaction = null;
    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     */
    protected $company_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CompanyGrpc\ThreadReactionStruct $thread_reaction
     *     @type int|string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.companyGrpc.ThreadReactionStruct thread_reaction = 1;</code>
     * @return \CompanyGrpc\ThreadReactionStruct|null
     */
    public function getThreadReaction()
    {
        return $this->thread_reaction;
    }

    public function hasThreadReaction()
    {
        return isset($this->thread_reaction);
    }

    public function clearThreadReaction()
    {
        unset($this->thread_reaction);
    }

    /**
     * Generated from protobuf field <code>.companyGrpc.ThreadReactionStruct thread_reaction = 1;</code>
     * @param \CompanyGrpc\ThreadReactionStruct $var
     * @return $this
     */
    public function setThreadReaction($var)
    {
        GPBUtil::checkMessage($var, \CompanyGrpc\ThreadReactionStruct::class);
        $this->thread_reaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

}

