<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для ReadMessageAdd
 *
 * Generated from protobuf message <code>companyGrpc.ReadMessageAddRequestStruct</code>
 */
class ReadMessageAddRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 company_id = 1;</code>
     */
    protected $company_id = 0;
    /**
     * Generated from protobuf field <code>string entity_type = 2;</code>
     */
    protected $entity_type = '';
    /**
     * Generated from protobuf field <code>string entity_map = 3;</code>
     */
    protected $entity_map = '';
    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string message_map = 5;</code>
     */
    protected $message_map = '';
    /**
     * Generated from protobuf field <code>int64 entity_message_index = 6;</code>
     */
    protected $entity_message_index = 0;
    /**
     * Generated from protobuf field <code>int64 message_created_at = 7;</code>
     */
    protected $message_created_at = 0;
    /**
     * Generated from protobuf field <code>int64 read_at = 8;</code>
     */
    protected $read_at = 0;
    /**
     * Generated from protobuf field <code>int32 table_shard = 9;</code>
     */
    protected $table_shard = 0;
    /**
     * Generated from protobuf field <code>int64 entity_meta_id = 10;</code>
     */
    protected $entity_meta_id = 0;
    /**
     * Generated from protobuf field <code>string entity_key = 11;</code>
     */
    protected $entity_key = '';
    /**
     * Generated from protobuf field <code>string message_key = 12;</code>
     */
    protected $message_key = '';
    /**
     * Generated from protobuf field <code>int32 db_shard = 13;</code>
     */
    protected $db_shard = 0;
    /**
     * Generated from protobuf field <code>bool is_force_show_participant = 14;</code>
     */
    protected $is_force_show_participant = false;
    /**
     * Generated from protobuf field <code>repeated int64 hide_read_participant_list = 15;</code>
     */
    private $hide_read_participant_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $company_id
     *     @type string $entity_type
     *     @type string $entity_map
     *     @type int|string $user_id
     *     @type string $message_map
     *     @type int|string $entity_message_index
     *     @type int|string $message_created_at
     *     @type int|string $read_at
     *     @type int $table_shard
     *     @type int|string $entity_meta_id
     *     @type string $entity_key
     *     @type string $message_key
     *     @type int $db_shard
     *     @type bool $is_force_show_participant
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $hide_read_participant_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 1;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entity_type = 2;</code>
     * @return string
     */
    public function getEntityType()
    {
        return $this->entity_type;
    }

    /**
     * Generated from protobuf field <code>string entity_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->entity_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entity_map = 3;</code>
     * @return string
     */
    public function getEntityMap()
    {
        return $this->entity_map;
    }

    /**
     * Generated from protobuf field <code>string entity_map = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityMap($var)
    {
        GPBUtil::checkString($var, True);
        $this->entity_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_map = 5;</code>
     * @return string
     */
    public function getMessageMap()
    {
        return $this->message_map;
    }

    /**
     * Generated from protobuf field <code>string message_map = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageMap($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 entity_message_index = 6;</code>
     * @return int|string
     */
    public function getEntityMessageIndex()
    {
        return $this->entity_message_index;
    }

    /**
     * Generated from protobuf field <code>int64 entity_message_index = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEntityMessageIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->entity_message_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 message_created_at = 7;</code>
     * @return int|string
     */
    public function getMessageCreatedAt()
    {
        return $this->message_created_at;
    }

    /**
     * Generated from protobuf field <code>int64 message_created_at = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->message_created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 read_at = 8;</code>
     * @return int|string
     */
    public function getReadAt()
    {
        return $this->read_at;
    }

    /**
     * Generated from protobuf field <code>int64 read_at = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->read_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 table_shard = 9;</code>
     * @return int
     */
    public function getTableShard()
    {
        return $this->table_shard;
    }

    /**
     * Generated from protobuf field <code>int32 table_shard = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTableShard($var)
    {
        GPBUtil::checkInt32($var);
        $this->table_shard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 entity_meta_id = 10;</code>
     * @return int|string
     */
    public function getEntityMetaId()
    {
        return $this->entity_meta_id;
    }

    /**
     * Generated from protobuf field <code>int64 entity_meta_id = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEntityMetaId($var)
    {
        GPBUtil::checkInt64($var);
        $this->entity_meta_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string entity_key = 11;</code>
     * @return string
     */
    public function getEntityKey()
    {
        return $this->entity_key;
    }

    /**
     * Generated from protobuf field <code>string entity_key = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->entity_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_key = 12;</code>
     * @return string
     */
    public function getMessageKey()
    {
        return $this->message_key;
    }

    /**
     * Generated from protobuf field <code>string message_key = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 db_shard = 13;</code>
     * @return int
     */
    public function getDbShard()
    {
        return $this->db_shard;
    }

    /**
     * Generated from protobuf field <code>int32 db_shard = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setDbShard($var)
    {
        GPBUtil::checkInt32($var);
        $this->db_shard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_force_show_participant = 14;</code>
     * @return bool
     */
    public function getIsForceShowParticipant()
    {
        return $this->is_force_show_participant;
    }

    /**
     * Generated from protobuf field <code>bool is_force_show_participant = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsForceShowParticipant($var)
    {
        GPBUtil::checkBool($var);
        $this->is_force_show_participant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 hide_read_participant_list = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHideReadParticipantList()
    {
        return $this->hide_read_participant_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 hide_read_participant_list = 15;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHideReadParticipantList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->hide_read_participant_list = $arr;

        return $this;
    }

}

