<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>companyGrpc.ThreadReactionStruct</code>
 */
class ThreadReactionStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string thread_map = 1;</code>
     */
    protected $thread_map = '';
    /**
     * Generated from protobuf field <code>string message_map = 2;</code>
     */
    protected $message_map = '';
    /**
     * Generated from protobuf field <code>int64 block_id = 3;</code>
     */
    protected $block_id = 0;
    /**
     * Generated from protobuf field <code>int64 block_message_index = 4;</code>
     */
    protected $block_message_index = 0;
    /**
     * Generated from protobuf field <code>int64 thread_message_index = 5;</code>
     */
    protected $thread_message_index = 0;
    /**
     * Generated from protobuf field <code>int64 reaction_uniq = 6;</code>
     */
    protected $reaction_uniq = 0;
    /**
     * Generated from protobuf field <code>string shard_id = 7;</code>
     */
    protected $shard_id = '';
    /**
     * Generated from protobuf field <code>int64 table_id = 8;</code>
     */
    protected $table_id = 0;
    /**
     * Generated from protobuf field <code>int64 user_id = 9;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 updated_at_ms = 10;</code>
     */
    protected $updated_at_ms = 0;
    /**
     * Generated from protobuf field <code>string ws_user_list = 11;</code>
     */
    protected $ws_user_list = '';
    /**
     * Generated from protobuf field <code>repeated .companyGrpc.EventVersionItem event_version_list = 12;</code>
     */
    private $event_version_list;
    /**
     * Generated from protobuf field <code>string ws_users = 13;</code>
     */
    protected $ws_users = '';
    /**
     * Generated from protobuf field <code>int64 is_ws_enabled = 14;</code>
     */
    protected $is_ws_enabled = 0;
    /**
     * Generated from protobuf field <code>string reaction_name = 15;</code>
     */
    protected $reaction_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $thread_map
     *     @type string $message_map
     *     @type int|string $block_id
     *     @type int|string $block_message_index
     *     @type int|string $thread_message_index
     *     @type int|string $reaction_uniq
     *     @type string $shard_id
     *     @type int|string $table_id
     *     @type int|string $user_id
     *     @type int|string $updated_at_ms
     *     @type string $ws_user_list
     *     @type \CompanyGrpc\EventVersionItem[]|\Google\Protobuf\Internal\RepeatedField $event_version_list
     *     @type string $ws_users
     *     @type int|string $is_ws_enabled
     *     @type string $reaction_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string thread_map = 1;</code>
     * @return string
     */
    public function getThreadMap()
    {
        return $this->thread_map;
    }

    /**
     * Generated from protobuf field <code>string thread_map = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setThreadMap($var)
    {
        GPBUtil::checkString($var, True);
        $this->thread_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_map = 2;</code>
     * @return string
     */
    public function getMessageMap()
    {
        return $this->message_map;
    }

    /**
     * Generated from protobuf field <code>string message_map = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageMap($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 block_id = 3;</code>
     * @return int|string
     */
    public function getBlockId()
    {
        return $this->block_id;
    }

    /**
     * Generated from protobuf field <code>int64 block_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockId($var)
    {
        GPBUtil::checkInt64($var);
        $this->block_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 block_message_index = 4;</code>
     * @return int|string
     */
    public function getBlockMessageIndex()
    {
        return $this->block_message_index;
    }

    /**
     * Generated from protobuf field <code>int64 block_message_index = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlockMessageIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->block_message_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 thread_message_index = 5;</code>
     * @return int|string
     */
    public function getThreadMessageIndex()
    {
        return $this->thread_message_index;
    }

    /**
     * Generated from protobuf field <code>int64 thread_message_index = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setThreadMessageIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->thread_message_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reaction_uniq = 6;</code>
     * @return int|string
     */
    public function getReactionUniq()
    {
        return $this->reaction_uniq;
    }

    /**
     * Generated from protobuf field <code>int64 reaction_uniq = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReactionUniq($var)
    {
        GPBUtil::checkInt64($var);
        $this->reaction_uniq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shard_id = 7;</code>
     * @return string
     */
    public function getShardId()
    {
        return $this->shard_id;
    }

    /**
     * Generated from protobuf field <code>string shard_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setShardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shard_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 table_id = 8;</code>
     * @return int|string
     */
    public function getTableId()
    {
        return $this->table_id;
    }

    /**
     * Generated from protobuf field <code>int64 table_id = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTableId($var)
    {
        GPBUtil::checkInt64($var);
        $this->table_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 9;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at_ms = 10;</code>
     * @return int|string
     */
    public function getUpdatedAtMs()
    {
        return $this->updated_at_ms;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at_ms = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAtMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ws_user_list = 11;</code>
     * @return string
     */
    public function getWsUserList()
    {
        return $this->ws_user_list;
    }

    /**
     * Generated from protobuf field <code>string ws_user_list = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setWsUserList($var)
    {
        GPBUtil::checkString($var, True);
        $this->ws_user_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .companyGrpc.EventVersionItem event_version_list = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEventVersionList()
    {
        return $this->event_version_list;
    }

    /**
     * Generated from protobuf field <code>repeated .companyGrpc.EventVersionItem event_version_list = 12;</code>
     * @param \CompanyGrpc\EventVersionItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEventVersionList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CompanyGrpc\EventVersionItem::class);
        $this->event_version_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ws_users = 13;</code>
     * @return string
     */
    public function getWsUsers()
    {
        return $this->ws_users;
    }

    /**
     * Generated from protobuf field <code>string ws_users = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setWsUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->ws_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_ws_enabled = 14;</code>
     * @return int|string
     */
    public function getIsWsEnabled()
    {
        return $this->is_ws_enabled;
    }

    /**
     * Generated from protobuf field <code>int64 is_ws_enabled = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsWsEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_ws_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reaction_name = 15;</code>
     * @return string
     */
    public function getReactionName()
    {
        return $this->reaction_name;
    }

    /**
     * Generated from protobuf field <code>string reaction_name = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setReactionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->reaction_name = $var;

        return $this;
    }

}

