<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_company.proto

namespace CompanyGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура описания топа
 *
 * Generated from protobuf message <code>companyGrpc.TopItem</code>
 */
class TopItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     */
    protected $position = 0;
    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>int64 is_disabled = 4;</code>
     */
    protected $is_disabled = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int|string $position
     *     @type int|string $count
     *     @type int|string $is_disabled
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoCompany::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     * @return int|string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int64 position = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkInt64($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int64 count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_disabled = 4;</code>
     * @return int|string
     */
    public function getIsDisabled()
    {
        return $this->is_disabled;
    }

    /**
     * Generated from protobuf field <code>int64 is_disabled = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsDisabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_disabled = $var;

        return $this;
    }

}

